version: '3.9'

services:

  frontend:
    build: encryption
    restart: always
    container_name: frontend
    stop_signal: SIGINT

  nginx:
    build: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    stop_signal: SIGINT

 